#!/bin/sh

# List directories in current directory or the given directory.
# usage: lsdir [-0AqR] [dir]
# -0	the list of directories is null terminated
# -A	list all directories including hidden ones; something like ls -A
# -q	listed directories are enclosed with double quotes; e.g. "directory name"
# -R	list directories recursively; something like ls -R

Prog=`basename $0`

fnUsage() { echo "usage: ${Prog} [-0qRA] [dir]" 1>&2; exit 1; }

while getopts ":0qRA" opt; do
  case $opt in
  	0)
  		NullTerminate="true"
  		;;
    q)
      	Quote="true"
      	;;
    R)
      	Recursive="true"
      	;;
    A)
    	A="A"
    	;;
    *)
      fnUsage
      ;;
  esac
done

shift $((OPTIND-1))

Dir="."
if [ "$1" ]
	then
		Dir="$1"
fi

fnLsDirRecursive() { ls -pR1${A} "$Dir" | grep '^.*:$' | sed 's/\(^.*\):$/\1\//'; }

fnLsDirNonRecursive() { ls -p1${A} "$Dir" | grep '^.*/$' | sed 's/^.*$/&/'; }

fnLsDir()
{
if [ $Recursive ] 
	then
		fnLsDirRecursive
	else
		fnLsDirNonRecursive
fi
}

if [ $Quote ]
	then
		Result=`fnLsDir | sed 's/^.*$/"&"/'`
	else
		Result=`fnLsDir`
fi

if [ ! "$Result" ]
then
	exit 0
fi

if [ $NullTerminate ]
	then
		printf "%s\0" "$Result"
	else
		printf "%s\n" "$Result"
fi

exit 0
