#!/bin/sh

Prog=`basename $0`

fnUsage() { echo "usage: ${Prog} source_dir destination_dir" 1>&2; exit 1; }

fnError() { echo "${Prog}: ${1}: ${2}" 1>&2; exit 1; }

#check for required arguments
#============================
if [  $# -ne 2 ]
then
	fnUsage
fi

#get arguments
#=============
Src=$1
Dest=$2

#validate arguments
#==================
if [ ! -e "$Src" ]
then
	fnError "$Src" "No such file or directory"
fi

if [ ! -e "$Dest" ]
then
	fnError "$Dest" "No such file or directory"
fi

if [ ! -d "$Src" ]
then
	fnError "$Src" "Not a directory"
fi

if [ ! -d "$Dest" ]
then
	fnError "$Dest" "Not a directory"
fi

#declare script specific functions
#=================================
fnMvFiles()
{
	src_folder=$1
	dest_folder=$2
	
	ls -Ap1 "$src_folder" | grep '^.*[^/]$' | while read -r file ;
	do
		mv "${src_folder}/${file}" "${dest_folder}/${file}"
	done 
}

fnMvDir()
{
	src=$1
	dest=$2
	src_basename=$3
	
	mkdir -p "${dest}/${src_basename}"
	fnMvFiles "$src" "${dest}/${src_basename}"

	lsdir -AR "$src" | while read -r file ;
	do
		file=`trim -f -t "${src}/" "$file"`
		file=`trim -e -t "/" "$file"`
		new_dir="${dest}/${src_basename}/${file}"
		old_dir="${src}/${file}"
		mkdir -p "$new_dir"
		fnMvFiles "${old_dir}" "$new_dir"
		rmdir "$old_dir" &> /dev/null 
	done 
	
	lsdir -qRA "$src" | xargs rmdir 
	rmdir "$src"
}

#start processing arguments
#==========================
SrcBasename=`basename "$Src"`
DestPath="${Dest}/${SrcBasename}"

if [ -e "$DestPath" ]
then
	#folder with same name already exists
	
	#check if the existing folder has any items
	num_items=`ls -A1 "$DestPath" | wc -l`
	
	if [ $num_items -gt 0 ]
	then
		#ask for confirmation for overwriting
		read -p "${Prog}: destination \"${DestPath}\" is not empty. overwrite [y/n]? " -n 1 -r
		echo	#move to next line
		if [[ ! $REPLY =~ ^[Yy]$ ]]
		then
   		 	exit 1
		fi
	fi
	
	#move to tmp hidden folder first
	tmp=".${SrcBasename}"
	fnMvDir "$Src" "$Dest" "$tmp"
	#overwrite folder
	#echo "rm -rf \"${DestPath}\""
	mv "${DestPath}" "$HOME/.trash"
	mv "${Dest}/${tmp}" "$DestPath"
else
	fnMvDir "$Src" "$Dest" "$SrcBasename"
fi

exit 0
