#!/bin/bash

usage() { echo "Usage: $0 dir" 1>&2; exit 1; }

if [ $# -eq 0 ]
	then
		usage
fi

for arg in "$@"
	do
	if [ -e "$arg" ] && [ $(dircount "$arg") -eq 1 ]
		then
			echo "moveout " `echo $arg`
			file=`echo "${arg%/}"/*`
			#echo "file=$file"
			if [ -d $file ]
				then
					cp -Rf $file "$arg/.."
					if [ -e $file ]
						then
							rm -rf $file
					fi
				else
					mv -f $file "$arg/.."
			fi
	fi
	
done