#!/bin/bash
# prepends filename to each line of the file

Prog=`basename $0`

fnUsage() { echo "usage: ${Prog} file" 1>&2; exit 1; }

if [[ -z "${1}" ]]
then
  fnUsage
fi

function fnMain() {
awk 'BEGIN {OFS=","} {print FILENAME,$0}' "${1}"
}

if [[ -t 0 ]] || [[ $# -gt 0 ]]
then
	# read from terminal stdin
	for arg in "$@"
	do
		fnMain "${arg}"
	done
else
	# read from file stdin
  while read -r line ; do
		fnMain "${line}"
  done
fi
