#!/bin/bash

Prog=`basename $0`

fnUsage() { echo "usage: ${Prog} [-d | -f] [-s size] name ... | pattern ..." 1>&2; exit 1; }

type=""
size=""

while getopts "dfs:" opt; do
    case "${opt}" in
        d|f)
            type=" -type ${opt}"
            ;;
        s)
            size=" -size ${OPTARG}"
            if [[ -z $size ]]; then
              fnUsage
            fi
            ;;
        *)
            fnUsage
            ;;
    esac
done

shift $((OPTIND-1))

if [ $# -eq 0 ]
	then
		fnUsage
fi

for arg in "$@"
do
		find .${type}${size} -name "$arg" -exec echo "remove {}" \; | grep -E '\.....?$'
done

read -p "Continue? (y/n): " -n 1 -r
echo 
if [[ $REPLY =~ ^[Yy]$ ]]
then
    for arg in "$@"
    do
            find .${type}${size} -name "$arg" -print0 | xargs -0 rm -rf 
    done
fi

