#!/bin/bash

# renames files in given directory with serial number

Prog=`basename $0`

fnUsage() { echo "usage: ${Prog} dir" 1>&2; exit 1; }

if [ $# -eq 0 ]
  then
    fnUsage
fi

dir="$1"

file_count=`ls -1 $dir | wc -l`
file_count=${file_count//[[:space:]]}
file_count=${#file_count}

a=1
for i in $dir/*; do
  file=`basename ${i}`
  ext="${file##*.}"

  new=$(printf "%0${file_count}d.${ext}" "$a") #04 pad to length of 4
  echo "rename: ${i} to ${dir}/${new}"
  let a=a+1
done

read -p "Continue? (y/n): " -n 1 -r
echo 
if [[ $REPLY =~ ^[Yy]$ ]]
then
  a=1
  for i in $dir/*; do
    file=`basename ${i}`
    ext="${file##*.}"

    new=$(printf "%0${file_count}d.${ext}" "$a") #04 pad to length of 4
    mv -- "${i}" "${dir}/${new}"
    let a=a+1
  done
fi
